### ISSUE TITLE
Walkie talkie error and other things found so far(Beta 1.09.5) 

### ISSUE THREAD

**Issue by Aketi** [ZPSNMRiHIssues/nmrihissues#757] opened 2015-09-27 04:15 UTC
![0e52954280573e82e522ada4f693a725](https://cloud.githubusercontent.com/assets/5096129/10121135/96bf4d7a-6518-11e5-80c9-08ed78bd7047.png)
This error was recorded as i was hosting the beta server. And, the third person model equipping it is bugged, it just floats around at the waist height.

Fire axe third person model is also bugged, it displays nothing. I remember this happens on 1.09.4 too(maybe even older?)

Zombie kid got no barricade-whacking animation (unsure).

No supply drop was made on nms_northway. Didn't hear any incoming heli, either. there was nothing on server log though. Haven't tried the debug mode.

Feedback: The barricade-whacking sound of zombies is the same sound as you drop the boards.
some people will get jumpy when actually they got more boards on their side. Please change if you can.

**Comment by Bubka3** [comment] 2015-09-27 16:08
Duplicate of #756 . Please use that issue for further comments.

**Closed** 2015-09-27 16:10 UTC
